app.env: dev

# aws
aws:
  url: http://localhost:4566
  id: development
  secret: development
  profile: default
  region: us-east-1

# consumers
consumers:
  users:
    queue-url: http://localhost:4566/000000000000/users-consumer
    max-workers: 2
    max-messages: 10

# target-app
target-app:
  endpoint: http://localhost:8000/users-consumer

# rest-pools
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 2000
        connection-timeout: 5000
  client:
    target-app:
      pool: default
