app.env: dev

topics:
  users:
    id: development
    secret: development
    profile: default
    address: http://localhost:4566
    region: us-east-1
    name: users-topic

consumers:
  users:
    id: development
    secret: development
    profile: default
    region: us-east-1
    name: users-consumer

# rest-pools
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 2000
        connection-timeout: 5000
  client:
    target-app:
      pool: default
