app.env: dev

aws:
  url: http://localhost:4566
  id: development
  secret: development
  profile: default
  region: us-east-1

topics:
  users:
    name: users-topic

consumers:
  users:
    name: users-consumer
    queue-url: http://localhost:4566/000000000000/users-consumer
    max-workers: 2
    max-messages: 10

# rest-pools
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 2000
        connection-timeout: 5000
  client:
    target-app:
      pool: default
