app.env: prod
protocol: https
log.level: info

host: 0.0.0.0
port: '8080'

# @TODO: aws by env
aws:
  url: http://localhost:4566
  region: us-east-1
  partition: aws

# queues-clients
queues:
  orders:
    name: queue-name
    url: https://domain/queue-name
    parallel: 2 # default is 2
    timeout: 1000

# consumers
consumers:
  orders:
    workers: 10 # default is instances core - 1

# pusher (your-app)
pusher:
  target-endpoint: https://{MY_APP}.{SCOPE}.dp.iskaypet.com/orders-consumer

# rest-pools
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 2000
        connection-timeout: 5000
  client:
    target-client:
      pool: default
