# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

tasks:
  download:
    desc: Run go mod tidy.
    cmds:
      - go mod tidy
  upgrade:
    desc: Check for latest direct dependencies.
    cmds:
      - go-mod-upgrade
  run:
    desc: Build the go EXECUTABLE.
    interactive: true
    cmds:
      - mkdir -p build/..
      - go build -v main.go
      - mv main build/
      - ./build/main  {{.CLI_ARGS}}
