app.env: local

public: http://localhost:8080
protocol: http
host: 127.0.0.1
port: 8080

# aws
aws:
  url: http://localhost:4566
  id: development
  secret: development
  profile: default
  region: us-east-1

# queues-clients
queues:
  orders:
    name: orders-consumer
    parallel: 2 # default is 2
    timeout: 1000

# consumers
consumers:
  orders:
    workers: 10 # default is instances core - 1

# pusher (your-app)
pusher:
  target-endpoint: http://localhost:4000/orders-consumer

# rest-pools
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 20000
        connection-timeout: 50000
  client:
    target-client:
      pool: default
