app.env: local

# aws
aws:
  url: http://localhost:4566
  id: development
  secret: development
  profile: default
  region: us-east-1

# queues-clients
queues:
  users:
    name: users-consumer
    parallel: 2 # default is 2
    timeout: 1000

# consumers
consumers:
  users:
    workers: 10 # default is instances core - 1

# pusher (your-app)
pusher:
  target-endpoint: http://localhost:8000/users-consumer

# rest-pools
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 2000
        connection-timeout: 5000
  client:
    target-client:
      pool: default
