app.env: local

public: http://localhost:8080
protocol: http
host: 127.0.0.1
port: 8080
log:
  level: debug

# aws
aws:
  url: http://localhost:4566
  partition: aws
  region: us-east-1


# queues-clients
queues:
  orders:
    name: orders-consumer
    url: http://localhost:4566/000000000000/orders-consumer
    parallel: 1 # default is  2
    timeout: 1000 # ms

# consumers
consumers:
  orders:
    workers: 2 # default is instances core - 1

# pusher (your-app)
pusher:
  target-endpoint: http://localhost:4000/orders-consumer

# rest-pools
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 20000            # ms
        connection-timeout: 50000 # ms
  client:
    target-client:
      pool: default
